language: julia
julia:
  - 0.5
os:
  - linux
addons:
  apt_packages:
    - gfortran
notifications:
  email: false
after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'ENV["DOCUMENTER_DEBUG"] = "true"; cd(Pkg.dir("Sims", "docs")); include("make.jl")'
  - julia -e 'cd(Pkg.dir("Sims")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'